---
title: "P8105_HW2_jl6648"
output: html_document
date: "2023-09-27"
---

```{r}
library(tidyverse)
library(dplyr)
```


```{r}
pols_df = 
  read_csv("fivethirtyeight_datasets/pols-month.csv") |>
  janitor::clean_names() |>
  separate(mon, into = c("year", "mon", "day"), sep = "-") |>
  mutate(year = as.numeric(year), 
          mon = as.numeric(mon), 
          day = as.numeric(day)) |>
  mutate(mon = month.abb[mon],
         president = case_when(prez_gop == "1" ~ "gop", prez_dem == "1" ~ "dem")) |>
  select(-c(prez_gop, prez_dem, day))
```

```{r}
snp_df =
  read_csv("fivethirtyeight_datasets/snp.csv") |>
  janitor::clean_names() |>
  separate(date, into = c("day", "mon", "year"), sep = "/") |>
  mutate(year = as.numeric(year), 
          mon = as.numeric(mon), 
          day = as.numeric(day)) |>
  mutate(mon = month.abb[mon]) |>
  select(year, mon, everything(), -c(day)) |>
  relocate(year, mon)
```

```{r}
unemploy_df =
  read_csv("fivethirtyeight_datasets/unemployment.csv") |>
  pivot_longer(
      Jan:Dec,
      names_to = "mon",
      values_to = "unemployment") |>
  rename(year = Year) |>
  relocate(year, mon)
```

```{r}
joindata_df =
  left_join(pols_df, snp_df, by = c("year", "mon"))

joindata_df2 =
  left_join(joindata_df, unemploy_df,  by = c("year", "mon"))
```

```{r}
Wheel_df =
  readxl::read_excel("202207 Trash Wheel Collection Data.xlsx",
  sheet = "Mr. Trash Wheel",
  range = "A2:N549") |>
  janitor::clean_names() |>
  drop_na("dumpster") |>
  mutate(homes_powered = weight_tons*500/30,
         year = as.integer(year), 
         dataset = "Mr. Trash") 
```

```{r}
professor_df =
  readxl::read_excel("202207 Trash Wheel Collection Data.xlsx",
  sheet = "Professor Trash Wheel",
  range = "A2:M96") |>
  janitor::clean_names() |>
  drop_na("dumpster") |>
  mutate(homes_powered = weight_tons*500/30,
         dataset = "Professor Trash" )
```

```{r}
Gwynnda_df =
  readxl::read_excel("202207 Trash Wheel Collection Data.xlsx",
  sheet = "Gwynnda Trash Wheel",
  range = "A2:K108") |>
  janitor::clean_names() |>
  drop_na("dumpster") |>
  mutate(homes_powered = weight_tons*500/30,
         dataset = "Gwynnda Trash")
```

```{r}
TrashWhell_combine =
  bind_rows(Wheel_df, professor_df, Gwynnda_df)
```

```{r}
baseline_df =
  read_csv("data_mci/MCI_baseline.csv") |>
  janitor::clean_names() |>
  mutate(
    sex = replace(sex, sex == 0, "Female"),
    sex = replace(sex, sex == 1, "Male"),
    apoe4 = replace(apoe4, apoe4 == 1, "Yes"),
    apoe4 = replace(apoe4, apoe4 == 0, "No")
  )

filter(baseline_df, age_at_onset > 0)

total_age =
  pull(baseline_df, current_age) 
  mean(total_age)
```

```{r}
filter(baseline_df, sex == "Female" & apoe4 == "Yes")
filter(baseline_df, sex == "Female")
```
63/221 = 0.285 = 28.5%

```{r}
amyloid_df =
  read_csv("data_mci/mci_amyloid.csv") |>
  janitor::clean_names() |>
  rename(id = study_id)
```

the study id in the "mci_amyloid.csv" dataset is inconsistent. id is the cue to find the participate appeared in both dataset. 
```{r}
participant_combine =
  left_join(baseline_df, amyloid_df, by = "id")
```
