P8105_HW2_jl6648
================
2023-09-27

``` r
library(tidyverse)
library(dplyr)
```

## problem 1

``` r
pols_df = 
  read_csv("fivethirtyeight_datasets/pols-month.csv") |>                #read dataset and clean names 
  janitor::clean_names() |> 
  separate(mon, into = c("year", "mon", "day"), sep = "-") |>            #separate the month variable
  mutate(year = as.numeric(year),  
          mon = as.numeric(mon), 
          day = as.numeric(day)) |>                                  # change new variables to numeric 
  mutate(mon = month.abb[mon],        #replace month number with name, create a new variable president
         president = case_when(prez_gop == "1" ~ "gop", prez_dem == "1" ~ "dem")) |> 
  select(-c(prez_gop, prez_dem, day))                                                  # drop variable 
```

Description of pols_df: The dataset contains 822 observations, 9
variables including year, mon, gov_gop, sen_gop, rep_gop, gov_dem,
sen_dem, rep_dem, and president. Variable mon is divided into three new
variable (year, mon day). The range of year is from 1947 to 2015.
president is a new variable combined with prez_gop and prez_dem. three
variable (prez_gop, prez_dem, day) is dropped from original dataset.

``` r
snp_df =
  read_csv("fivethirtyeight_datasets/snp.csv") |>           #read the dataset and clean variable names.
  janitor::clean_names() |>
  separate(date, into = c("day", "mon", "year"), sep = "/") |>            #separate the month variable
  mutate(year = as.numeric(year), 
          mon = as.numeric(mon),                                     # change new variables to numeric 
          day = as.numeric(day)) |>
  mutate(mon = month.abb[mon]) |>                                      #replace month number with name
  select(year, mon, everything(), -c(day)) |>                                         # select columns 
  relocate(year, mon)                                  #organize year and month as the leading columns
```

Description of snp_df, the dataset contains 787 observations, three
variables including year, mon, close. Use the same method to separate
mon variable into year, mon, day from original dataset. Then, drop the
day variable. The range of year is from 1950 to 2015.

``` r
unemploy_df =
  read_csv("fivethirtyeight_datasets/unemployment.csv") |> #read the dataset and clean variable names.
  pivot_longer( 
      Jan:Dec,                                             #switch “wide” to “long” format
      names_to = "mon",
      values_to = "unemployment") |>
  rename(year = Year) |>                          #change the name, keep consistent with other dataset
  relocate(year, mon)                             #organize year and month as the leading columns
```

Description of unemploy_df, The dataset contains 816 observations, three
variables including year, mon, unemployment. Pivot_long function is used
to reshape the data, then create a new variable unemployment. Rename the
variable Year to year, keep it consistent with other dataset. The range
of year is from 1948 to 2015.

``` r
joindata_df =
  left_join(pols_df, snp_df, by = c("year", "mon")) #join the  two datasets by same column "year"&"mon"

joindata_df2 =                                                     #merging unemploy_df into the result
  left_join(joindata_df, unemploy_df,  by = c("year", "mon"))
```

Description of joindata_df and joindata_df2: joindata_df joined by
pols_df and snp_df with same column year and mon. It contains 822
observations and 10 variables. The range of year is from 1947 to 2015.
joindata_df joined by joindata_df and unemploy_df with the same column
year and mon. It contains 822 observations and 11 variables. The range
of year is from 1947 to 2015.

## problem 2

``` r
Wheel_df =
  readxl::read_excel("202309 Trash Wheel Collection Data.xlsx", 
  sheet = "Mr. Trash Wheel",                                 #read dataset with correct sheet and range
  range = "A2:N586") |>
  janitor::clean_names() |>                                                               #clean names 
  drop_na("dumpster") |>  #omit na. 
  mutate(homes_powered = weight_tons*500/30,                    #calculate the homes_powered variable 
         year = as.integer(year), 
         dataset = "Mr. Trash")                                                  #specify the dataset 
```

Description of Wheel_df: The data contains 584 observations and
dumpster, month, year, date, weight_tons, volume_cubic_yards,
plastic_bottles, polystyrene, cigarette_butts, glass_bottles,
plastic_bags, wrappers, sports_balls, homes_powered, dataset variables.
The homes_powered is a new variable created by using weight_tons
variable and based on the note of calculation formula. dataset is
another new variable used to distinguish the origin of observations
after merging these three datasets.

``` r
professor_df =
  readxl::read_excel("202309 Trash Wheel Collection Data.xlsx",
  sheet = "Professor Trash Wheel",
  range = "A2:M108") |>                                     #read dataset with correct sheet and range
  janitor::clean_names() |>                                                               #clean names 
  drop_na("dumpster") |>
  mutate(homes_powered = weight_tons*500/30,                      #calculate the homes_powered variable
         dataset = "Professor Trash" )                                            #specify the dataset
```

Description of professor_df: The data contains 106 observations and
dumpster, month, year, date, weight_tons, volume_cubic_yards,
plastic_bottles, polystyrene, cigarette_butts, glass_bottles,
plastic_bags, wrappers, homes_powered, dataset variables. Total weight
of trash is 216.26. Same with the Wheel_df dataset, The homes_powered is
a new variable created by using weight_tons variable and based on the
note of calculation formula. dataset variable show that these
observations come from Professor Trash dataset.

``` r
Gwynnda_df =
  readxl::read_excel("202309 Trash Wheel Collection Data.xlsx",
  sheet = "Gwynnda Trash Wheel",
  range = "A2:L157") |>                                      #read dataset with correct sheet and range
  janitor::clean_names() |>                                                               #clean names 
  drop_na("dumpster") |>
  mutate(homes_powered = weight_tons*500/30,                      #calculate the homes_powered variable
         dataset = "Gwynnda Trash")                                               #specify the dataset
```

``` r
Gwynnda_cigarette =
filter(Gwynnda_df, month == "July" & year == 2021) 
  sum(Gwynnda_cigarette$cigarette_butts)
```

    ## [1] 16300

Description of Gwynnda_df: The data contains 155 observations and
dumpster, month, year, date, weight_tons, volume_cubic_yards,
plastic_bottles, polystyrene, cigarette_butts, plastic_bags, wrappers,
homes_powered, dataset variables. Total cigarette butts in July of 2021
is 1.63^{4}. Same with two datasets above, The homes_powered is a new
variable created by using weight_tons variable and based on the note of
calculation formula. dataset variable show that these observations come
from Gwynnda Trash dataset.

``` r
TrashWhell_combine =
  bind_rows(Wheel_df, professor_df, Gwynnda_df)                                 #combine these dataset 
```

Description of TrashWhell_combine: The dataset combine three data above
with 845 observations and dumpster, month, year, date, weight_tons,
volume_cubic_yards, plastic_bottles, polystyrene, cigarette_butts,
glass_bottles, plastic_bags, wrappers, sports_balls, homes_powered,
dataset variables. dataset variable specify the observations come from
which dataset.

## problem 3

``` r
baseline_df =
  read_csv("data_mci/MCI_baseline.csv", na = ".") |>                             #import dataset
  janitor::clean_names() |>                                                      #clean names 
  mutate(                                    #use mutate to indicate sex and apoe4 in a appropriate way
    sex = replace(sex, sex == 0, "Female"),
    sex = replace(sex, sex == 1, "Male"),
    apoe4 = replace(apoe4, apoe4 == 1, "Yes"),
    apoe4 = replace(apoe4, apoe4 == 0, "No"))
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): ID, Current Age, Sex, Education, apoe4, Age at onset
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

how many people develop MCI?

``` r
baseline_mci_df =
   baseline_df |>
  #remove participants who don't develop MCI or already developed MCI before study started
  filter(!(current_age >= age_at_onset | is.na(age_at_onset)))
```

How many participants were recruited?

``` r
baseline_df_recruit =
    baseline_df |>
    filter(current_age < age_at_onset | is.na(age_at_onset))
                                    #remove participants who already developed MCI before study started
```

To import dataset, read_csv function. is used to read the data and
janitor::clean_names is used to further clean names of a data frame.
mutate is used to represent sex and APOE4 carrier status in a
appropriate way. baseline_df is a dataset that is created after basic
cleaning and mutation. It contains 483 observations and id, current_age,
sex, education, apoe4, age_at_onset variabls.

There are 479 participants are recruited, 93 of them develop MCI. To
calculate how many participants are recruited, we need to remove
participants who already developed MCI before study started, which means
keep participants who develop MCI later or don’t develop MCI at all. To
calculate the how many people develop MCI, we need further remove people
who don’t develop MCI at all.

``` r
total_age =
  pull(baseline_df, current_age)                                   #calculate the mean of baseline age
  mean(total_age)
```

    ## [1] 65.04679

The average baseline age is 65.04679 by average all participants’
baseline age.

``` r
filter(baseline_df, sex == "Female" & apoe4 == "Yes")             #select females who are apoe4 carrier
```

    ## # A tibble: 63 × 6
    ##       id current_age sex    education apoe4 age_at_onset
    ##    <dbl>       <dbl> <chr>      <dbl> <chr>        <dbl>
    ##  1     1        63.1 Female        16 Yes           NA  
    ##  2     2        65.6 Female        20 Yes           NA  
    ##  3    22        67.3 Female        20 Yes           74.6
    ##  4    26        64.8 Female        20 Yes           71.1
    ##  5    34        64.8 Female        16 Yes           NA  
    ##  6    39        68.3 Female        16 Yes           70.2
    ##  7    43        67.1 Female        16 Yes           71.6
    ##  8    47        66.1 Female        12 Yes           NA  
    ##  9    50        67.6 Female        18 Yes           NA  
    ## 10    52        63.2 Female        16 Yes           NA  
    ## # ℹ 53 more rows

``` r
filter(baseline_df, sex == "Female")                                                     #select female
```

    ## # A tibble: 211 × 6
    ##       id current_age sex    education apoe4 age_at_onset
    ##    <dbl>       <dbl> <chr>      <dbl> <chr>        <dbl>
    ##  1     1        63.1 Female        16 Yes           NA  
    ##  2     2        65.6 Female        20 Yes           NA  
    ##  3     4        69.8 Female        16 No            NA  
    ##  4     8        67.2 Female        18 No            NA  
    ##  5     9        66.7 Female        16 No            NA  
    ##  6    10        64.1 Female        18 No            NA  
    ##  7    11        69.5 Female        16 No            NA  
    ##  8    12        66.2 Female        18 No            NA  
    ##  9    14        58.4 Female        20 No            66.2
    ## 10    16        64.9 Female        16 No            NA  
    ## # ℹ 201 more rows

There are 211 females and 63 of them are apoe4 carriers. 63/211 = 0.298
= 29.8% Therefore, 29.8% female are apoe4 carriers

``` r
amyloid_df =
  read_csv("data_mci/mci_amyloid.csv") |>                                             #import dataset 
  janitor::clean_names() |>
  rename(id = study_id,
         year_0 = baseline,
         year_2 = time_2,
         year_4 = time_4,
         year_6 = time_6,
         year_8 = time_8) |>                                     #rename to make the variable consistent
  pivot_longer(
    year_0:year_8,                                                            #make the dataset longer 
    names_to = "time",
    values_to = "value"
  )
```

To import dataset, read_csv function. is used to read the data and
janitor::clean_names is used to further clean names of a data frame. The
dataset contains 2435 observations and id, time, value variabls.
Pivot_longer is used to make the data longer instead of wider. The
“study id” in the “mci_amyloid.csv” dataset is inconsistent, so it is
renamed to “id”. It is the cue to find the participate appeared in both
dataset.

``` r
baseline_only = anti_join(baseline_df_recruit, amyloid_df, by = "id")
amyloid_only = anti_join(amyloid_df, baseline_df_recruit, by = "id")
```

8 participants only occur in the baseline dataset. 16 participants only
occur in the amyloid dataset.

``` r
participant_combine =
  inner_join(baseline_df_recruit, amyloid_df, by = "id")                      #join two datasets by id 
write.csv(participant_combine, "participant_combine.csv")                             #export the data
```

After joining two dataset together, dataset contains 2355 observations
and id, current_age, sex, education, apoe4, age_at_onset, time, value
variables. Specificlly 471 number of participants appears in both
dataset.
